# Generated by Django 6.0 on 2026-03-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
